In [ ]:
N-Dimensional array:

In [1]:
import numpy as np

In [2]:
array_of_one = np.array([1,2,3])

array_of_one

array([1, 2, 3])

In [5]:
import numpy as np


In [6]:
array_one = np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [9]:
numbers = [9,8,7,6,5]

array_two = np.array(numbers)

array_two

array([9, 8, 7, 6, 5])

In [10]:
array_of_zeros = np.zeros((2,3))

array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array_of_ones = np.ones((2,3))

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
array_of_ones_int = np.ones((4,5),dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
Identity matrix: Structure and shape of an identity matrix

In [17]:
array_eye = np.eye(3)

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
req: By using numpy I want to have a even numbers printed till 10.....??

In [19]:
array_of_evens = np.arange(2,11,2)

array_of_evens

array([ 2,  4,  6,  8, 10])

In [24]:
array_of_odds = np.arange(1,11,2)

array_of_odds

array([1, 3, 5, 7, 9])