In [ ]:
Numpy:

In [ ]:
Understanding the identity matrix:

In [1]:
import numpy as np

In [3]:
array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
Array of floats:

In [6]:
array_of_floats = np.arange(0,2,0.4)

array_of_floats

array([0. , 0.4, 0.8, 1.2, 1.6])

In [ ]:
Creating 2Dimensional array

In [7]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [8]:
array_2d.shape

(2, 3)

In [9]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [11]:
x.shape

(6,)

In [ ]:
req: Changing the above to 2_dimensional array ?

In [12]:
array_nd = x.reshape(2,3)

array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
array_nd.shape

(2, 3)

In [15]:
array_nd = x.reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
Printing Array:  1-Dimensional Array

In [16]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [17]:
a.shape

(6,)

In [ ]:
2-Dimensional Array :

In [18]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
b.shape

(4, 3)

In [ ]:
3-Dimensional Array :

In [20]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
c.shape

(2, 3, 4)