In [ ]:
Statistical operations in Numpy:

In [1]:
import numpy as np

In [4]:
test_scores = np.array([32.99,33.56,56,98,21,38.69,43.49,78.80,45.78,78.96])

In [5]:
print(test_scores)

[32.99 33.56 56.   98.   21.   38.69 43.49 78.8  45.78 78.96]


In [6]:
type(test_scores)

numpy.ndarray

In [ ]:
req: i want to calculate the mean of test scores.

In [7]:
print('Mean test scores of the students: ')
print(np.mean(test_scores))

Mean test scores of the students: 
52.727


In [ ]:
req: please find the median of the test scores.

In [8]:
print('Median test scores of the students: ')
print(np.median(test_scores))

Median test scores of the students: 
44.635000000000005


In [ ]:
working on the dataset provided.....>

In [ ]:
req: bringing that to our jupyter environment.

In [ ]:
Calculate the below
Mean
Mode 
Medium
Standard deviation
Variance

In [14]:
x = np.genfromtxt('salary.csv',delimiter=',')

In [15]:
x

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [34]:
mean = np.mean(x)
median = np.median(x)
sd = np.std(x)
variance = np.var(x)


In [35]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('Standard deviation = %i' %sd)
print('variance = %i' %variance)

Mean = 55894
Median = 48000
Standard deviation = 55170
variance = 3043770333


In [ ]:
Introduction to iteration:

In [36]:
a = np.arange(11)**2

In [37]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [38]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
iteration through multi dimensional array

In [40]:
students = np.array([['diksha','neha','satya','ashok'],
                     [35,40,45,44],
                     [25,40,45,40]])

In [41]:
students

array([['diksha', 'neha', 'satya', 'ashok'],
       ['35', '40', '45', '44'],
       ['25', '40', '45', '40']], dtype='<U6')